"""New

Revision ID: 697c886076aa
Revises: d2c17ce753b3
Create Date: 2024-06-01 23:51:20.420099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697c886076aa'
down_revision: Union[str, None] = 'd2c17ce753b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Laptop shop', sa.Column('laptop_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Laptop shop', 'laptop_price')
    # ### end Alembic commands ###
