"""new

Revision ID: 6cbaa37cdc29
Revises: 43a0091e3a74
Create Date: 2024-06-07 12:47:03.628312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbaa37cdc29'
down_revision: Union[str, None] = '43a0091e3a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shoppers', 'money',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shoppers', 'money',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
