"""New

Revision ID: 7bb8ee8dce9c
Revises: e6207f12024e
Create Date: 2024-06-01 20:21:25.307129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb8ee8dce9c'
down_revision: Union[str, None] = 'e6207f12024e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Laptop shop', 'laptop_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Laptop shop', sa.Column('laptop_price', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
