"""New

Revision ID: b0a0617ccb6a
Revises: aa28ecae047c
Create Date: 2024-06-07 12:43:08.524709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a0617ccb6a'
down_revision: Union[str, None] = 'aa28ecae047c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shoppers', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shoppers', 'password')
    # ### end Alembic commands ###
