"""New

Revision ID: e6207f12024e
Revises: e23ce8278cc7
Create Date: 2024-06-01 20:04:27.176355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6207f12024e'
down_revision: Union[str, None] = 'e23ce8278cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Common Shoppers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_number_of_purchases', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('High Class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_number_of_purchases', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Laptop shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laptop_cpu', sa.String(), nullable=False),
    sa.Column('laptop_gpu', sa.Text(), nullable=False),
    sa.Column('laptop_display_inch', sa.Float(), nullable=False),
    sa.Column('laptop_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Laptop shop_id'), 'Laptop shop', ['id'], unique=False)
    op.create_table('Middle Class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_number_of_purchases', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Pistol Armory')
    op.drop_table('Pistol Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pistol Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['Pistol Armory.pistol_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pistol Armory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pistol_type', sa.VARCHAR(), nullable=False),
    sa.Column('pistol_name', sa.TEXT(), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Middle Class')
    op.drop_index(op.f('ix_Laptop shop_id'), table_name='Laptop shop')
    op.drop_table('Laptop shop')
    op.drop_table('High Class')
    op.drop_table('Common Shoppers')
    # ### end Alembic commands ###
